---
- name: tomcat installation
  hosts: all
  become: "yes"
  tasks:
    - name: java installation
      ansible.builtin.apt:
        name: "{{java_packages}}"
        state: "present"
        update_cache: "true"
    - name: creating group
      ansible.builtin.group:
        name: "{{group}}"
        state: "present"
    - name: creating user
      ansible.builtin.user:
        create_home : "yes"
        group: "{{group}}"
        home : "{{home_dir}}"
        name: "{{user}}"
        shell: "{{shell}}"
        system: "true"
        state: "present"
    # - name: tomcat url
    #   ansible.builtin.get_url:
    #     url: "{{tomcat_url}}"
    #     dest: /tmp/apache-tomcat-10.0.10.tar.gz
    - name: copying url 
      ansible.builtin.unarchive:
        src: "{{tomcat_url}}"
        dest: "{{home_dir}}"
        remote_src : "false"
    

       

      



        