---
- name: activity1
  hosts: all
  become: true
  tasks:
    - name: apache installation
      ansible.builtin.apt:
        name: 
          - apache2
        state: "present"
    - name: enable and start apache2
      ansible.builtin.systemd_service:
        name:
          - service
        enabled: "true"
        state : "started"
        